pipeline:
  build:
    image: plugins/docker
    tag: latest
    dockerfile: Dockerfile
    repo: strum355/refund-backend
    secrets: [ docker_username, docker_password ]
    when:
      event: [ push, tag ]
      branch: master    
  ssh:
    image: appleboy/drone-ssh
    host: leela.netsoc.co
    username: strum355
    port: 22
    secrets: [ ssh_password ]
    script:
      - docker pull strum355/refund-backend
      - docker stop noah-refund
      - docker rm noah-refund
      - docker run -d -p 5555:8080 --name noah-refund -v (pwd)/UCC/CS3305/java/application.properties:/refund/application.properties strum355/refund-backend
    when:
      event: [ push, tag ]
      branch: master
  webhook:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: back-end 
    icon_url: https://cdn.worldvectorlogo.com/logos/drone.svg
    username: Refund CI
    template: >
      {{#success build.status}}
        Build {{build.number}} succeeded. Good job.
      {{else}}
        Build {{build.number}} failed. Fix me please.
      {{/success}}
    when:
      event: [ push, tag ]
      branch: master      